version: "3.7"

services:
  hawkscan:
    image: stackhawk/hawkscan
    network_mode: host
    environment:
      - API_KEY=$HAWK_API_KEY
      - HAWK_APP_ID
      - HAWK_ENV
    volumes:
      - type: bind
        source: .
        target: /hawk
    tty: true
